"use strict"

const PLUGIN_VERSION = "0.3.4"
const HELPER_VERSION = "0.2.2"
const PROTOCOL_VERSION = 1
const MAX_FRAME_BYTES = 8 * 1024 * 1024
const DEFAULT_HELPER_TIMEOUT_MS = 10_000
const CAPTURE_HELPER_TIMEOUT_MS = 20_000
const STATE_TTL_MS = 30_000
const WINDOW_TTL_MS = 10 * 60 * 1000

module.exports = {
  CAPTURE_HELPER_TIMEOUT_MS,
  DEFAULT_HELPER_TIMEOUT_MS,
  HELPER_VERSION,
  MAX_FRAME_BYTES,
  PLUGIN_VERSION,
  PROTOCOL_VERSION,
  STATE_TTL_MS,
  WINDOW_TTL_MS,
}
